# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### ethereum config options #####
# Boolean specifying if this node is a validator
is_validator = "true"

# File containing unencrypted private key
# Used to sign eth transactions interacting with the rootchain 
# Default directory is $HOME/.plasmad/config/
ethereum_privkey_file = "priv1"

# Ethereum rootchain contract address
ethereum_rootchain = "0x5cae340fb2c2bb0a2f194a95cda8a1ffdc9d2f85"

# Node URL for eth client
ethereum_nodeurl = "ws://127.0.0.1:8545"

# Minimum fee a validator accepts to include a transaction in a block
minimum_fees = "0"

# Number of Ethereum blocks until a submitted block header is considered final
ethereum_finality = "0"
